config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  get 'trash/trash_em'
  get 'trash/trash_em_all'
  root 'lists#index'
  #root 'home#home_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :lists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def home_index
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  # GET /lists or /lists.json
  def index
    @lists = List.all
    
  end

  # GET /lists/1 or /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    #@list = List.new
    @list = current_user.lists.build
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists or /lists.json
  def create
    #@list = List.new(list_params)
    @list = current_user.lists.build(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to lists_url(@list), notice: "List was successfully created." }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1 or /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to lists_url(@list), notice: "List was successfully updated." }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1 or /lists/1.json
  def destroy
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url, notice: "List was successfully deleted." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @list = current_user.lists.find_by(id: params[:id])
     redirect_to lists_path, notice: "Not Authorized to Edit This List" if @list.nil?

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_params
      params.require(:list).permit(:description, :completed, :user_id)
    end
end

app/controllers/trash_controller.rb
class TrashController < ApplicationController

    def trash_em
        @trash_em = List.where(:completed => true).destroy_all
        redirect_to lists_url(@list), notice: 'All Marked Items where successfuly deleted'
    end

    def trash_em_all
        @trash_em_all = List.all.destroy_all
        redirect_to lists_url(@list), notice: 'All Items where successfully deleted'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/home/home_index.html.erb
<h1>Home</h1>
<p>Pagina in constructie</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">

<%= notice %>
  
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoAppLocal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    
  </head>

  <body>

  <%= render "lists/navbar" %>
    <div class="container">
    <br/>
    <% if notice %>
    <%= render 'layouts/alerts' %>
  <% end %>

    <br/>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: list) do |form| %>
  <% if list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :description, class:"form-control", placeholder:"List Name" %>
    
  </div>
  <br/>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <div class="field form-group">
    <%= form.number_field :user_id, id: :list_user_id, class:"form-control", value: current_user.id, type: :hidden %>
    
  </div>
  
  <br/>
  <div class="actions">
    <%= form.submit class:"btn btn-warning"%>
  </div>
<% end %>

app/views/lists/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
    
    <%= link_to "ToDoApp", root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      <% if user_signed_in? %>

        <li class="nav-item">
        <%= link_to "Lists", lists_path, class:"nav-link" %>         
        </li>

        <li class="nav-item">
        <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
        </li>

        <% else %>

        <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
        <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
       
        <% end %>       
        
      </ul>
         
    </div>
  </div>
</nav>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form', list: @list %>
<br/>
<%= link_to 'Show', @list, class:"btn btn-warning" %> 
<%= link_to 'Back', lists_path, class:"btn btn-warning" %>

app/views/lists/index.html.erb
<table class="table table bordered">

  <tbody>
    <% @lists.each do |list| %>

      <% if list.user == current_user %>

      <% if list.completed %>

      <tr class="table-secondary ">
        <td class="striker"><%= link_to list.description, edit_list_path(list)%></td>     
        <td>
          <center>
            <%= form_for(list) do |f| %>
            <%= f.text_field :description, type:'hidden' %>
            <%= f.text_field :user_id, type:'hidden' %>
            <%= f.check_box :completed, :checked => false, :style => 'visibility: hidden' %>
            <%= f.submit "Uncross", class: 'btn btn-outline-danger btn btn-sm' %>
            <% end %>
          </center>
        </td<>
       
        <td><%= button_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-dark" %></td>
      </tr>

      <% else %>

      <tr>
        <td><%= link_to list.description, edit_list_path(list)%></td> 
        <td>
        <center>
            <%= form_for(list) do |f| %>
            <%= f.text_field :description, type:'hidden' %>
            <%= f.text_field :user_id, type:'hidden' %>
            <%= f.check_box :completed, :checked => true, :style => 'visibility: hidden' %>
            <%= f.submit "Cross off", class: 'btn btn-outline-danger btn btn-sm' %>
            <% end %>
          </center>
        
        </td<>
    
        <td><%= button_to 'Delete', list, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-dark" %></td>
      </tr>

      <% end %>

      <% end %>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New List', new_list_path, class:"btn btn-warning" %>
<br/>
<br/>
<%= link_to 'Delete Marked Items', trash_trash_em_path, data: { confirm: 'Are you sure?' }, class:"btn btn-dark" %>
<%= link_to 'Delete All Items', trash_trash_em_all_path, data: { confirm: 'Are you sure?' }, class:"btn btn-dark" %>

app/views/lists/new.html.erb
<div class="card">
  <div class="card-header">
    <h4>Add New List</h4>
</div>

<div class="card-body">
    <%= render 'form', list: @list %>
</div>
  </div>

<br/>
<%= link_to 'Back', lists_path, class:"btn btn-warning" %>

app/views/lists/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @list.description %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @list.completed %>
</p>

<%= link_to 'Edit', edit_list_path(@list), class:"btn btn-warning" %> 
<%= link_to 'Back', lists_path, class:"btn btn-warning" %>